// host-webpack-react/src/App.tsx
import { init } from '@module-federation/enhanced/runtime';
import Hero from './components/Hero';
import Remote from './components/Remote';
import RemoteInfo from './components/RemoteInfo';

init({
  name: '@demo/app-main',
  remotes: [
    {
      name: '@demo/remote',
      entry: `${process.env.REMOTE_HOST}/mf-manifest.json?v=${Date.now()}`,
      alias: 'remote',
    }
  ]
});

const App = () => {
  return (
    <div>
      <Hero />
      <Remote />
      <RemoteInfo />
    </div>
  );
};

export default App;

// host-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RemoteComponent } from './components/remote/remote.component';
import { RemoteInfoComponent } from './components/remote-info/remote-info.component';
import { HeroComponent } from './components/hero/hero.component';
import { init } from '@module-federation/enhanced/runtime';
import { environment } from '../environments/environment';
init({
  name: '@demo/app-main',
  remotes: [
    {
      name: '@demo/remote',
      entry: `${environment.REMOTE_HOST}/mf-manifest.json?v=${Date.now()}`,
      alias: 'remote',
    },
  ],
});
@Component({
  selector: 'app-root',
  imports: [RemoteComponent, HeroComponent, RemoteInfoComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'host-angular';
}

<app-hero></app-hero>
<app-remote></app-remote>
<app-remote-info></app-remote-info>
