// host-angular/src/app/components/hero/hero.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';

@Component({
  selector: 'app-hero',
  imports: [],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css',
})
export class HeroComponent implements OnInit, OnDestroy {
  number: number | null = null;

  private eventHandler = (event: Event) => {
    const customEvent = event as CustomEvent;
    this.number = customEvent.detail?.count || 0;
  };
  ngOnInit(): void {
    document.addEventListener('build', this.eventHandler);
  }

  ngOnDestroy(): void {
    document.removeEventListener('build', this.eventHandler);
  }
}

<div>
  <h1>This Is Host Angular</h1>
  <p>Counter value Remote {{ number }}</p>
</div>

// host-webpack-react/src/components/Hero.tsx
import React, { useEffect } from 'react';

const Hero = () => {
  const [number, setNumber] = React.useState(null);
  useEffect(() => {
    const eventHandler = (event: Event) => {
      const customEvent = event as CustomEvent;
      setNumber(customEvent.detail?.count || 0);
    };
    document.addEventListener('build', eventHandler);
    return () => {
      document.removeEventListener('build', eventHandler);
    };
  }, []);
  return (
    <div>
      <h1>This Is Host Webpack React</h1>
      <p>Counter value Remote {number} </p>
    </div>
  );
};

export default Hero;
