// host-angular/src/app/components/remote-info/remote-info.component.ts
import { JsonPipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { loadRemote } from '@module-federation/enhanced/runtime';

@Component({
  selector: 'app-remote-info',
  imports: [JsonPipe],
  templateUrl: './remote-info.component.html',
  styleUrl: './remote-info.component.css'
})
export class RemoteInfoComponent implements OnInit {
  info: any;

  ngOnInit(): void {
    loadRemote('remote/Info').then((module:any) => {
      this.info = module.default;
    }).catch((error) => {
      console.error('Error loading remote module:', error);
    });
  }

}

<div>
    <h2>Remote Info</h2>
    <pre>{{ info | json }}</pre>
</div>

// host-webpack-react/src/components/RemoteInfo.tsx
import { loadRemote } from '@module-federation/enhanced/runtime';
import React, { useEffect } from 'react';

const RemoteInfo = () => {
  const [info, setInfo] = React.useState(null);

  useEffect(() => {
     loadRemote('remote/Info').then((module:any) => {
      setInfo(module.default);
    }).catch((error) => {
      console.error('Error loading remote module:', error);
    });
  }, []);

  return (
    <div>
      <h2>Remote Info</h2>
      {info && <pre>{JSON.stringify(info, null, 2)}</pre>}
    </div>
  );
};

export default RemoteInfo;
